"""SQLModel model declarations."""

from .audit_log import AuditLog
from .dataset import (
    DataCleaningJob,
    DataCleaningJobStatus,
    Dataset,
    DatasetSourceType,
    DatasetStatus,
    DatasetVersion,
    DatasetVersionStatus,
    DatasetCleaningTemplate,
    DatasetCleaningAssignment,
    CleaningStepType,
    QualityEvaluationJob,
    QualityEvaluationStatus,
    DatasetFormatVersion,
    DatasetFormatType,
    DatasetFormatStatus,
)
from .refresh_token import RefreshToken
from .role import Role, RolePermission, WorkspaceMemberRole
from .user import User
from .verification_code import VerificationCode
from .workspace import Project, Workspace, WorkspaceMember, WorkspaceStatus, ProjectStatus
from .training import (
    TrainingAdapterType,
    TrainingEvent,
    TrainingJob,
    TrainingJobStatus,
    TrainingRun,
    TrainingTemplate,
    TrainingWizardDraft,
    TrainingMetricSample,
    TrainingMetricName,
    TrainingAlertRule,
    TrainingAlertOperator,
    TrainingAlertStatus,
    TrainingAlert,
    TrainingSnapshot,
    TrainingSnapshotTriggerType,
)
from .evaluation import (
    EvaluationTemplate,
    EvaluationTaskType,
    EvaluationJob,
    EvaluationJobStatus,
    EvaluationTriggerMode,
    EvaluationFeedback,
    EvaluationFeedbackKind,
    EvaluationFeedbackStatus,
)
from .model_registry import RegisteredModel, ModelVersion, ModelVersionStatus
from .inference import (
    InferenceApiKey,
    InferenceCall,
    InferenceCallStatus,
    InferenceUsage,
    UsageWindowScope,
)
from .governance import (
    KanbanCard,
    KanbanEntityType,
    KanbanStage,
    KanbanStatus,
    Comment,
    CommentEntityType,
    ApprovalRequest,
    ApprovalStatus,
    ApprovalTask,
    ApprovalTaskStatus,
)
from .notification import (
    NotificationChannel,
    NotificationChannelType,
    NotificationDeliveryStatus,
    NotificationRecord,
)
from .knowledge import (
    KnowledgeEntry,
    KnowledgeEntryType,
    KnowledgeEntryVersion,
)
from .runtime_monitoring import (
    RuntimeAlert,
    RuntimeAlertOperator,
    RuntimeAlertRule,
    RuntimeAlertStatus,
    RuntimeMetricName,
)
from .deployment import Deployment, DeploymentEvent, DeploymentInstance, DeploymentStatus

__all__ = [
    "AuditLog",
    "DataCleaningJob",
    "DataCleaningJobStatus",
    "Dataset",
    "DatasetSourceType",
    "DatasetStatus",
    "DatasetVersion",
    "DatasetVersionStatus",
    "DatasetCleaningTemplate",
    "DatasetCleaningAssignment",
    "CleaningStepType",
    "QualityEvaluationJob",
    "QualityEvaluationStatus",
    "DatasetFormatVersion",
    "DatasetFormatType",
    "DatasetFormatStatus",
    "TrainingAdapterType",
    "TrainingTemplate",
    "TrainingJob",
    "TrainingJobStatus",
    "TrainingRun",
    "TrainingEvent",
    "TrainingWizardDraft",
    "TrainingMetricSample",
    "TrainingMetricName",
    "TrainingAlertRule",
    "TrainingAlertOperator",
    "TrainingAlertStatus",
    "TrainingAlert",
    "TrainingSnapshot",
    "TrainingSnapshotTriggerType",
    "EvaluationTemplate",
    "EvaluationTaskType",
    "EvaluationJob",
    "EvaluationJobStatus",
    "EvaluationTriggerMode",
    "EvaluationFeedback",
    "EvaluationFeedbackKind",
    "EvaluationFeedbackStatus",
    "RegisteredModel",
    "ModelVersion",
    "ModelVersionStatus",
    "InferenceApiKey",
    "InferenceCall",
    "InferenceCallStatus",
    "InferenceUsage",
    "UsageWindowScope",
    "KanbanCard",
    "KanbanEntityType",
    "KanbanStage",
    "KanbanStatus",
    "Comment",
    "CommentEntityType",
    "ApprovalRequest",
    "ApprovalStatus",
    "ApprovalTask",
    "ApprovalTaskStatus",
    "NotificationChannel",
    "NotificationChannelType",
    "NotificationDeliveryStatus",
    "NotificationRecord",
    "KnowledgeEntry",
    "KnowledgeEntryType",
    "KnowledgeEntryVersion",
    "RuntimeMetricName",
    "RuntimeAlertOperator",
    "RuntimeAlertStatus",
    "RuntimeAlertRule",
    "RuntimeAlert",
    "Deployment",
    "DeploymentInstance",
    "DeploymentEvent",
    "DeploymentStatus",
    "Project",
    "ProjectStatus",
    "RefreshToken",
    "Role",
    "RolePermission",
    "User",
    "VerificationCode",
    "Workspace",
    "WorkspaceMember",
    "WorkspaceMemberRole",
    "WorkspaceStatus",
]
